#!/usr/bin/env bash
# Generate the Codex integration from canonical .agents inputs.
#
# --check writes nothing and exits 1 when tracked generated output has drifted
# from its tracked inputs: .codex/agents/*.toml and the three .codex/ symlinks.
# It skips the gitignored .codex/config.toml, which has no tracked baseline.
# Run it on its own — after the generator it compares fresh writes to themselves
# and can never fail.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
check=false
trust=true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)    check=true; shift ;;
    # For tests and dry runs: the trust step writes ~/.codex/config.toml, which
    # belongs to the operator, not to this repository.
    --no-trust) trust=false; shift ;;
    *) echo "usage: sync-codex.sh [--check] [--no-trust]" >&2; exit 2 ;;
  esac
done

status=0
python3 - "$repo" "$check" <<'PY' || status=$?
import json
import os
import sys
import tempfile

repo, check = sys.argv[1], sys.argv[2] == "true"
agents = os.path.join(repo, ".agents")
codex = os.path.join(repo, ".codex")
sys.path.insert(0, agents)
from mcp_registry import resolve_registry
import reader_config
import toggles as toggle_rules

def load(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as error:
        raise SystemExit(f"sync-codex: invalid JSON in {path}: {error}")

def quoted(value):
    return json.dumps(value, ensure_ascii=False)

def write(path, content):
    if check:
        try:
            with open(path, encoding="utf-8") as f:
                actual = f.read()
        except FileNotFoundError:
            actual = None
        if actual != content:
            failures.append(os.path.relpath(path, repo))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.islink(path):
        os.unlink(path)
    fd, temporary = tempfile.mkstemp(dir=os.path.dirname(path), prefix=".sync-codex-")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(temporary, path)
    print("generated " + os.path.relpath(path, repo))

def link(path, target):
    if check:
        if not os.path.islink(path) or os.readlink(path) != target:
            failures.append(os.path.relpath(path, repo))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Temp+rename, like write(): unlink-then-symlink leaves a window with no
    # hooks.json at all, and Codex with no hooks is worse than Codex with hooks
    # whose trust hash the re-link just invalidated. mkstemp cannot name a
    # symlink, so the name carries the pid — a fixed one collides between two
    # concurrent syncs and strands the loser's destination absent, which is the
    # failure this replaces. os.replace renames the link itself, never the
    # target it points at.
    temporary = f"{path}.sync-codex-{os.getpid()}"
    if os.path.lexists(temporary):
        os.unlink(temporary)
    os.symlink(target, temporary)
    os.replace(temporary, path)
    print("linked " + os.path.relpath(path, repo))

def contract_body(name):
    path = os.path.join(agents, "personas", name + ".md")
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    body, heading_seen = [], False
    for line in lines:
        if line.startswith("## "):
            heading_seen = True
        if not heading_seen and (line.startswith("> ") or line.strip() == ">"):
            continue
        # export-scaffold.py's region markers are source annotations, not
        # content; the agent reads this body and should never see them.
        if line.strip() in ("<!-- colloid-only -->", "<!-- /colloid-only -->"):
            continue
        body.append(line)
    return "".join(body).strip()

def toml_multiline(value):
    # Literal, not basic: persona prose carries regexes and paths, and a basic
    # string would read a backslash as an escape and a trailing one as a line
    # continuation.
    if "'''" in value:
        raise SystemExit("sync-codex: custom agent instructions contain TOML delimiter")
    return "'''\n" + value + "\n'''\n"

def agent_toml(name, description):
    header = (
        "<!-- GENERATED by .agents/sync-codex.sh. Edit .agents/personas and run the sync script. -->\n\n"
    )
    return (
        f"name = {quoted(name)}\n"
        f"description = {quoted(description)}\n"
        "developer_instructions = " + toml_multiline(header + contract_body(name))
    )

def codex_config():
    """The .codex/config.toml body: the base file plus one record per server."""
    example = load(os.path.join(agents, "config.json.example"))
    local = load(os.path.join(agents, "config.json"))
    registry = load(os.path.join(agents, "mcp.json")).get("mcpServers", {})
    # The reader tier's launch config is a local path resolve_registry validates
    # for every entry, enabled or not. Generated here too, because this script
    # runs standalone on a fresh clone — where sync-mcp.sh has not written it yet.
    reader_config.write(agents)
    registry = resolve_registry(registry, repo, "sync-codex")
    toggles = toggle_rules.merge(example, local)

    config = open(os.path.join(agents, "codex", "config.toml"), encoding="utf-8").read().rstrip() + "\n"
    for name in sorted(registry):
        setting = toggles.get(name, {})
        enabled = setting.get("enabled") is True and setting.get("codex_enabled", True) is True
        server = registry[name]
        server_type = server.get("type")
        table = f'[mcp_servers.{quoted(name)}]'
        if server_type not in ("stdio", "http"):
            print(f"sync-codex: skipping {name}; Codex requires stdio or streamable HTTP", file=sys.stderr)
            continue

        url = server.get("url", "")
        if server_type == "http" and enabled and "${" in url:
            # Codex cannot interpolate the credential, so the server cannot run
            # here. Mask it rather than omitting it: with no record at all, a
            # same-name server from user or plugin config loads unmasked.
            print(f"sync-codex: disabling {name} for Codex; it cannot interpolate URL credentials",
                  file=sys.stderr)
            enabled = False

        config += "\n" + table + "\n"
        config += f"enabled = {str(enabled).lower()}\n"

        # Every record carries its transport, disabled ones included: Codex
        # validates the merged entry, and a record with no transport is invalid
        # unless some lower layer happens to supply one. Nothing guarantees that.
        # debt: codex-mcp-transport-collision
        if server_type == "stdio":
            config += f"command = {quoted(server['command'])}\n"
            if server.get("args"):
                config += "args = [" + ", ".join(quoted(value) for value in server["args"]) + "]\n"
            if server.get("cwd"):
                config += f"cwd = {quoted(server['cwd'])}\n"
            if server.get("env"):
                config += f"\n[mcp_servers.{quoted(name)}.env]\n"
                for key, value in sorted(server["env"].items()):
                    config += f"{key} = {quoted(value)}\n"
        else:
            headers = server.get("headers", {})
            auth = headers.get("Authorization") if isinstance(headers, dict) else None
            config += f"url = {quoted(url)}\n"
            if isinstance(auth, str) and auth.startswith("Bearer ${") and auth.endswith("}"):
                config += f"bearer_token_env_var = {quoted(auth[9:-1])}\n"
            elif headers:
                print(f"sync-codex: skipping headers for {name}; only bearer environment headers are portable", file=sys.stderr)
    return config

# Every output is built before any of it is written. contract_body raises on a
# missing persona and toml_multiline on one carrying the TOML delimiter, and a
# throw part-way through the flush leaves .codex/ half-generated. The one write
# this phase does make is the reader tier's launch config, which is a
# precondition rather than an output: resolve_registry validates its path, and
# it derives from nothing but the extensions directory.
outputs = [
    (os.path.join(codex, "agents", "implementer.toml"), agent_toml(
        "implementer",
        "Delegate one bounded implementation unit after the plan is settled.",
    )),
    (os.path.join(codex, "agents", "mechanic.toml"), agent_toml(
        "mechanic",
        "Delegate mechanical bounded edits with one obvious result.",
    )),
    (os.path.join(codex, "agents", "explorer.toml"), agent_toml(
        "explorer",
        "Trace codebase structure and evidence for one bounded question without editing.",
    )),
    (os.path.join(codex, "agents", "qa-verifier.toml"), agent_toml(
        "qa-verifier",
        "Verify changed tests, APIs, and web behavior with executable evidence.",
    )),
    (os.path.join(codex, "agents", "reviewer.toml"), agent_toml(
        "reviewer",
        "Independently review a plan or diff against repository rules and stated intent.",
    )),
    (os.path.join(codex, "agents", "researcher.toml"), agent_toml(
        "researcher",
        "Delegate research that depends on current or external facts. Return cited evidence with confidence and date.",
    )),
    (os.path.join(codex, "agents", "learning-reporter.toml"), agent_toml(
        "learning-reporter",
        "Create a learning-focused session report that links each engineering decision to the code that implements it.",
    )),
]

# .codex/config.toml is the one output here that is gitignored: it derives from
# the gitignored config.json, so no tracked baseline exists to compare it
# against, and on a fresh clone it is absent entirely. --check gates committed
# output, so it skips this — which is also what keeps --check read-only, since
# building the config writes the reader tier's launch file.
if not check:
    outputs.append((os.path.join(codex, "config.toml"), codex_config()))

# The flush. Nothing above this line has touched .codex/.
failures = []
for path, content in outputs:
    write(path, content)

# Linked last, because re-linking hooks.json invalidates the trust hash of every
# hook it changes and an untrusted hook does not run. The wrapper re-trusts
# immediately after this script returns, so the disarmed window is one step wide
# and does not span the generation above.
link(os.path.join(codex, "hooks.json"), "../.agents/codex/hooks.json")
link(os.path.join(codex, "hooks", "adapter.sh"), "../../.agents/codex/adapter.sh")
link(os.path.join(codex, "hooks", "README.md"), "../../.agents/codex/README.md")

if failures:
    print("sync-codex: generated output is stale: " + ", ".join(failures), file=sys.stderr)
    raise SystemExit(1)
PY

# Rewriting hooks.json invalidates the trust hash of every hook it changed, and
# an untrusted hook does not run. Re-trust what was just deployed, so the sync
# leaves the hooks armed rather than silently disarmed. --check writes nothing,
# so it has nothing to re-trust.
#
# This runs even when generation failed. hooks.json is a symlink to a constant
# canonical target, so a failed re-link leaves the previous link pointing at the
# same file: re-trusting is correct either way, and leaving the hooks disarmed
# because a persona would not build is the worse outcome. $status still carries
# the failure out.
if [[ "$check" != "true" && "$trust" == "true" ]]; then
  if ! "$repo/.agents/codex/trust-hooks.py" "$repo"; then
    if [[ "$status" -eq 0 ]]; then status=1; fi
  fi
fi

# Warning only, read-only, no Codex process: safe on every run, including
# --check. It follows the re-trust so a crash here cannot disarm the hooks.
"$repo/.agents/codex/check-mcp-conflicts.py" "$repo"

exit "$status"
