#!/usr/bin/env bash
# Generate the Codex integration from canonical .agents inputs.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
check=false
trust=true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)    check=true; shift ;;
    # For tests and dry runs: the trust step writes ~/.codex/config.toml, which
    # belongs to the operator, not to this repository.
    --no-trust) trust=false; shift ;;
    *) echo "usage: sync-codex.sh [--check] [--no-trust]" >&2; exit 2 ;;
  esac
done

python3 - "$repo" "$check" <<'PY'
import json
import os
import sys
import tempfile

repo, check = sys.argv[1], sys.argv[2] == "true"
agents = os.path.join(repo, ".agents")
codex = os.path.join(repo, ".codex")

def load(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as error:
        raise SystemExit(f"sync-codex: invalid JSON in {path}: {error}")

def quoted(value):
    return json.dumps(value, ensure_ascii=False)

def write(path, content):
    if check:
        try:
            with open(path, encoding="utf-8") as f:
                actual = f.read()
        except FileNotFoundError:
            actual = None
        if actual != content:
            failures.append(os.path.relpath(path, repo))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.islink(path):
        os.unlink(path)
    fd, temporary = tempfile.mkstemp(dir=os.path.dirname(path), prefix=".sync-codex-")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(temporary, path)
    print("generated " + os.path.relpath(path, repo))

def link(path, target):
    if check:
        if not os.path.islink(path) or os.readlink(path) != target:
            failures.append(os.path.relpath(path, repo))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.lexists(path):
        os.unlink(path)
    os.symlink(target, path)
    print("linked " + os.path.relpath(path, repo))

def contract_body(name):
    path = os.path.join(agents, "personas", name + ".md")
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    body, heading_seen = [], False
    for line in lines:
        if line.startswith("## "):
            heading_seen = True
        if not heading_seen and (line.startswith("> ") or line.strip() == ">"):
            continue
        body.append(line)
    return "".join(body).strip()

def toml_multiline(value):
    # Literal, not basic: persona prose carries regexes and paths, and a basic
    # string would read a backslash as an escape and a trailing one as a line
    # continuation.
    if "'''" in value:
        raise SystemExit("sync-codex: custom agent instructions contain TOML delimiter")
    return "'''\n" + value + "\n'''\n"

def agent_toml(name, description):
    header = (
        "<!-- GENERATED by .agents/sync-codex.sh. Edit .agents/personas and run the sync script. -->\n\n"
    )
    return (
        f"name = {quoted(name)}\n"
        f"description = {quoted(description)}\n"
        "developer_instructions = " + toml_multiline(header + contract_body(name))
    )

example = load(os.path.join(agents, "config.json.example"))
local = load(os.path.join(agents, "config.json"))
registry = load(os.path.join(agents, "mcp.json")).get("mcpServers", {})
toggles = {name: dict(value) for name, value in example.get("mcp", {}).get("servers", {}).items() if isinstance(value, dict)}
local_servers = local.get("mcp", {}).get("servers", {})
if isinstance(local_servers, dict):
    for name, value in local_servers.items():
        if isinstance(value, dict):
            toggles.setdefault(name, {}).update(value)

failures = []
link(os.path.join(codex, "hooks.json"), "../.agents/codex/hooks.json")
link(os.path.join(codex, "hooks", "adapter.sh"), "../../.agents/codex/adapter.sh")
link(os.path.join(codex, "hooks", "README.md"), "../../.agents/codex/README.md")

config = open(os.path.join(agents, "codex", "config.toml"), encoding="utf-8").read().rstrip() + "\n"
for name in sorted(registry):
    setting = toggles.get(name, {})
    enabled = setting.get("enabled") is True and setting.get("codex_enabled", True) is True
    server = registry[name]
    server_type = server.get("type")
    table = f'[mcp_servers.{quoted(name)}]'
    if server_type not in ("stdio", "http"):
        print(f"sync-codex: skipping {name}; Codex requires stdio or streamable HTTP", file=sys.stderr)
        continue

    url = server.get("url", "")
    if server_type == "http" and enabled and "${" in url:
        # Codex cannot interpolate the credential, so the server cannot run
        # here. Mask it rather than omitting it: with no record at all, a
        # same-name server from user or plugin config loads unmasked.
        print(f"sync-codex: disabling {name} for Codex; it cannot interpolate URL credentials",
              file=sys.stderr)
        enabled = False

    config += "\n" + table + "\n"
    config += f"enabled = {str(enabled).lower()}\n"

    # Every record carries its transport, disabled ones included: Codex
    # validates the merged entry, and a record with no transport is invalid
    # unless some lower layer happens to supply one. Nothing guarantees that.
    # debt: codex-mcp-transport-collision
    if server_type == "stdio":
        config += f"command = {quoted(server['command'])}\n"
        if server.get("args"):
            config += "args = [" + ", ".join(quoted(value) for value in server["args"]) + "]\n"
        if server.get("env"):
            config += f"\n[mcp_servers.{quoted(name)}.env]\n"
            for key, value in sorted(server["env"].items()):
                config += f"{key} = {quoted(value)}\n"
    else:
        headers = server.get("headers", {})
        auth = headers.get("Authorization") if isinstance(headers, dict) else None
        config += f"url = {quoted(url)}\n"
        if isinstance(auth, str) and auth.startswith("Bearer ${") and auth.endswith("}"):
            config += f"bearer_token_env_var = {quoted(auth[9:-1])}\n"
        elif headers:
            print(f"sync-codex: skipping headers for {name}; only bearer environment headers are portable", file=sys.stderr)

write(os.path.join(codex, "config.toml"), config)
write(os.path.join(codex, "agents", "researcher.toml"), agent_toml(
    "researcher",
    "Delegate research that depends on current or external facts. Return cited evidence with confidence and date.",
))
write(os.path.join(codex, "agents", "learning-reporter.toml"), agent_toml(
    "learning-reporter",
    "Create a learning-focused session report that links each engineering decision to the code that implements it.",
))

if failures:
    print("sync-codex: generated output is stale: " + ", ".join(failures), file=sys.stderr)
    raise SystemExit(1)
PY

# Rewriting hooks.json invalidates the trust hash of every hook it changed, and
# an untrusted hook does not run. Re-trust what was just deployed, so the sync
# leaves the hooks armed rather than silently disarmed. --check must not write.
if [[ "$check" != "true" && "$trust" == "true" ]]; then
  "$repo/.agents/codex/trust-hooks.py" "$repo"
fi
