#!/usr/bin/env bash
# Generate the Codex integration from canonical .agents inputs.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
check=false
if [[ "${1:-}" == "--check" ]]; then
  check=true
  shift
fi
[[ $# -eq 0 ]] || { echo "usage: sync-codex.sh [--check]" >&2; exit 2; }

python3 - "$repo" "$check" <<'PY'
import json
import os
import sys
import tempfile

repo, check = sys.argv[1], sys.argv[2] == "True"
agents = os.path.join(repo, ".agents")
codex = os.path.join(repo, ".codex")

def load(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as error:
        raise SystemExit(f"sync-codex: invalid JSON in {path}: {error}")

def quoted(value):
    return json.dumps(value, ensure_ascii=False)

def write(path, content):
    if check:
        try:
            with open(path, encoding="utf-8") as f:
                actual = f.read()
        except FileNotFoundError:
            actual = None
        if actual != content:
            failures.append(os.path.relpath(path, repo))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.islink(path):
        os.unlink(path)
    fd, temporary = tempfile.mkstemp(dir=os.path.dirname(path), prefix=".sync-codex-")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(temporary, path)
    print("generated " + os.path.relpath(path, repo))

def link(path, target):
    if check:
        if not os.path.islink(path) or os.readlink(path) != target:
            failures.append(os.path.relpath(path, repo))
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.lexists(path):
        os.unlink(path)
    os.symlink(target, path)
    print("linked " + os.path.relpath(path, repo))

def contract_body(name):
    path = os.path.join(agents, "personas", name + ".md")
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    body, heading_seen = [], False
    for line in lines:
        if line.startswith("## "):
            heading_seen = True
        if not heading_seen and (line.startswith("> ") or line.strip() == ">"):
            continue
        body.append(line)
    return "".join(body).strip()

def toml_multiline(value):
    if '"""' in value:
        raise SystemExit("sync-codex: custom agent instructions contain TOML delimiter")
    return '"""\n' + value + '\n"""\n'

def agent_toml(name, description):
    header = (
        "<!-- GENERATED by .agents/sync-codex.sh. Edit .agents/personas and run the sync script. -->\n\n"
    )
    return (
        f"name = {quoted(name)}\n"
        f"description = {quoted(description)}\n"
        "developer_instructions = " + toml_multiline(header + contract_body(name))
    )

example = load(os.path.join(agents, "config.json.example"))
local = load(os.path.join(agents, "config.json"))
registry = load(os.path.join(agents, "mcp.json")).get("mcpServers", {})
toggles = {name: dict(value) for name, value in example.get("mcp", {}).get("servers", {}).items() if isinstance(value, dict)}
local_servers = local.get("mcp", {}).get("servers", {})
if isinstance(local_servers, dict):
    for name, value in local_servers.items():
        if isinstance(value, dict):
            toggles.setdefault(name, {}).update(value)

failures = []
link(os.path.join(codex, "hooks.json"), "../.agents/codex/hooks.json")
link(os.path.join(codex, "hooks", "adapter.sh"), "../../.agents/codex/adapter.sh")
link(os.path.join(codex, "hooks", "README.md"), "../../.agents/codex/README.md")

config = open(os.path.join(agents, "codex", "config.toml"), encoding="utf-8").read().rstrip() + "\n"
for name in sorted(registry):
    setting = toggles.get(name, {})
    if setting.get("enabled") is not True or setting.get("codex_enabled", True) is not True:
        continue
    server = registry[name]
    server_type = server.get("type")
    table = f'[mcp_servers.{quoted(name)}]'
    if server_type == "stdio":
        config += "\n" + table + "\n"
        config += f"command = {quoted(server['command'])}\n"
        if server.get("args"):
            config += "args = [" + ", ".join(quoted(value) for value in server["args"]) + "]\n"
        if server.get("env"):
            config += f"\n[mcp_servers.{quoted(name)}.env]\n"
            for key, value in sorted(server["env"].items()):
                config += f"{key} = {quoted(value)}\n"
    elif server_type == "http":
        url = server.get("url", "")
        headers = server.get("headers", {})
        auth = headers.get("Authorization") if isinstance(headers, dict) else None
        if "${" in url:
            print(f"sync-codex: skipping {name}; Codex cannot safely interpolate URL credentials", file=sys.stderr)
            continue
        config += "\n" + table + "\n" + f"url = {quoted(url)}\n"
        if isinstance(auth, str) and auth.startswith("Bearer ${") and auth.endswith("}"):
            config += f"bearer_token_env_var = {quoted(auth[9:-1])}\n"
        elif headers:
            print(f"sync-codex: skipping headers for {name}; only bearer environment headers are portable", file=sys.stderr)
    else:
        print(f"sync-codex: skipping {name}; Codex requires stdio or streamable HTTP", file=sys.stderr)

write(os.path.join(codex, "config.toml"), config)
write(os.path.join(codex, "agents", "researcher.toml"), agent_toml(
    "researcher",
    "Delegate research that depends on current or external facts. Return cited evidence with confidence and date.",
))
write(os.path.join(codex, "agents", "learning-reporter.toml"), agent_toml(
    "learning-reporter",
    "Create a learning-focused session report that links each engineering decision to the code that implements it.",
))

if failures:
    print("sync-codex: generated output is stale: " + ", ".join(failures), file=sys.stderr)
    raise SystemExit(1)
PY
