#!/usr/bin/env bash
# Sync Claude agent definitions from .agents/config.json
#
# Reads model routing from .agents/config.json and regenerates
# .claude/agents/*.md with the correct frontmatter. Each agent's body is taken
# from its source contract in .agents/ (orchestrator meta blockquotes stripped).
#
# Usage:
#   .agents/sync-claude-agents.sh
#
# Do not hand-edit files in .claude/agents/ — they are generated.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config="$repo/.agents/config.json"
agents_dir="$repo/.claude/agents"
src_dir="$repo/.agents"

mkdir -p "$agents_dir"

python3 - "$config" "$agents_dir" "$src_dir" <<'PY'
import json, os, sys

config_path, agents_dir, src_dir = sys.argv[1:]

# config.json is gitignored + per-repo; a fresh clone has only the .example.
# Fall back to it, then to empty defaults, so sync never dies on a clean checkout.
cfg = {}
for candidate in (config_path, config_path + ".example"):
    try:
        with open(candidate, encoding="utf-8") as f:
            cfg = json.load(f)
        break
    except Exception:
        continue

# Agent registry: one entry per generated definition. `model_key` indexes
# cfg["models"]; a null/absent model omits the frontmatter line (inherit parent).
AGENTS = [
    {
        "name": "researcher",
        "model_key": "researcher",
        "source": "researcher.md",
        "description": "Delegate research tasks that turn on current or external facts — library APIs, version compatibility, best practices, security implications, anything load-bearing where a wrong answer changes shipped code. Invoked via Task(subagent_type='researcher', prompt='[genome stamp] + [research question]').",
    },
    {
        "name": "learning-reporter",
        "model_key": "learning_reporter",
        "source": "learning-reporter.md",
        "description": "Generate a learning-focused session report for a junior reviewing the work — pairs each engineering decision and tradeoff with the actual code (file:line) that embodies it, written to docs/learning/. In pairing mode the report is produced inline by default; dispatch this subagent when the user asks to persist it to a file. Invoked via Task(subagent_type='learning-reporter', prompt='[decision-brief] + [changed files]'). Exempt from genome stamping — prepend no stamp.",
    },
]

header = (
    "<!-- GENERATED by .agents/sync-claude-agents.sh — do not hand-edit. "
    "Edit .agents/config.json and run the sync script. -->\n"
)

for agent in AGENTS:
    model = cfg.get("models", {}).get(agent["model_key"])
    model_line = f"model: {model}" if model else ""

    # Strip orchestrator meta blockquotes: blockquotes before the first ## heading
    # are instructions for the orchestrator; blockquotes after it are contract
    # examples for the agent and stay.
    with open(os.path.join(src_dir, agent["source"]), encoding="utf-8") as f:
        lines = f.readlines()

    body_lines = []
    seen_heading = False
    for line in lines:
        if line.startswith("## "):
            seen_heading = True
        if not seen_heading and (line.startswith("> ") or line.strip() == ">"):
            continue
        body_lines.append(line)

    body = "".join(body_lines).strip()

    frontmatter_parts = ["---", f"name: {agent['name']}", f"description: {agent['description']}"]
    if model_line:
        frontmatter_parts.append(model_line)
    frontmatter_parts.append("---")
    frontmatter = "\n".join(frontmatter_parts)

    # Frontmatter MUST start on line 1 — Claude Code only registers an agent
    # whose `---` is the first byte of the file. The GENERATED banner therefore
    # sits just below the closing `---`, inside the markdown body.
    output = frontmatter + "\n" + header + "\n" + body + "\n"

    out_path = os.path.join(agents_dir, agent["name"] + ".md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)

    print("generated " + out_path + (f" (model: {model})" if model else " (no model override)"))
PY
