#!/usr/bin/env bash
# Sync Claude agent definitions from their tracked inputs
#
# Reads model routing from .agents/config.json.example and regenerates
# .claude/agents/*.md with the correct frontmatter. Each agent's body is taken
# from its source contract in .agents/ (orchestrator meta blockquotes stripped).
#
# Usage:
#   .agents/sync-claude-agents.sh [--check]
#
# --check writes nothing and exits 1 when a generated agent definition has
# drifted from its tracked inputs. .claude/agents/*.md is committed, so drift
# there ships a definition contradicting the persona it claims to carry. Run it
# on its own — after the generator it compares fresh writes to themselves.
#
# Do not hand-edit files in .claude/agents/ — they are generated.
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
check=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) check=true; shift ;;
    *) echo "usage: sync-claude-agents.sh [--check]" >&2; exit 2 ;;
  esac
done
config="$repo/.agents/config.json.example"
agents_dir="$repo/.claude/agents"
src_dir="$repo/.agents/personas"

[[ "$check" == "true" ]] || mkdir -p "$agents_dir"

python3 - "$config" "$agents_dir" "$src_dir" "$check" <<'PY'
import json, os, sys

config_path, agents_dir, src_dir, check = sys.argv[1:]
check = check == "true"

# config_path is config.json.example, never the gitignored, per-repo config.json:
# `model:` lands in the frontmatter of a committed file, so reading the local
# config would commit one operator's machine-local routing and make every other
# checkout read as drifted.
cfg = {}
try:
    with open(config_path, encoding="utf-8") as f:
        cfg = json.load(f)
except Exception:
    pass
if not isinstance(cfg, dict):
    cfg = {}

# Agent registry: one entry per generated definition. `model_key` indexes
# cfg["models"]; a null/absent model omits the frontmatter line (inherit parent).
AGENTS = [
    {
        "name": "researcher",
        "model_key": "researcher",
        "source": "researcher.md",
        "description": "Delegate research tasks that turn on current or external facts — library APIs, version compatibility, best practices, security implications, anything load-bearing where a wrong answer changes shipped code. Invoked via Task(subagent_type='researcher', prompt='[genome stamp] + [research question]').",
    },
    {
        "name": "learning-reporter",
        "model_key": "learning_reporter",
        "source": "learning-reporter.md",
        "description": "Generate a learning-focused session report for a junior reviewing the work — pairs each engineering decision and tradeoff with the actual code (file:line) that embodies it, written to docs/learning/. In pairing mode the report is produced inline by default; dispatch this subagent when the user asks to persist it to a file. Invoked via Task(subagent_type='learning-reporter', prompt='[decision-brief] + [changed files]'). Exempt from genome stamping — prepend no stamp.",
    },
]

header = (
    "<!-- GENERATED by .agents/sync-claude-agents.sh — do not hand-edit. "
    "Edit .agents/personas, or models in .agents/config.json.example, "
    "and run the sync script. -->\n"
)

failures = []
for agent in AGENTS:
    model = cfg.get("models", {}).get(agent["model_key"])
    model_line = f"model: {model}" if model else ""

    # Strip orchestrator meta blockquotes: blockquotes before the first ## heading
    # are instructions for the orchestrator; blockquotes after it are contract
    # examples for the agent and stay.
    with open(os.path.join(src_dir, agent["source"]), encoding="utf-8") as f:
        lines = f.readlines()

    body_lines = []
    seen_heading = False
    for line in lines:
        if line.startswith("## "):
            seen_heading = True
        if not seen_heading and (line.startswith("> ") or line.strip() == ">"):
            continue
        # export-scaffold.py's region markers are source annotations, not
        # content; the agent reads this body and should never see them.
        if line.strip() in ("<!-- colloid-only -->", "<!-- /colloid-only -->"):
            continue
        body_lines.append(line)

    body = "".join(body_lines).strip()

    frontmatter_parts = ["---", f"name: {agent['name']}", f"description: {agent['description']}"]
    if model_line:
        frontmatter_parts.append(model_line)
    frontmatter_parts.append("---")
    frontmatter = "\n".join(frontmatter_parts)

    # Frontmatter MUST start on line 1 — Claude Code only registers an agent
    # whose `---` is the first byte of the file. The GENERATED banner therefore
    # sits just below the closing `---`, inside the markdown body.
    output = frontmatter + "\n" + header + "\n" + body + "\n"

    out_path = os.path.join(agents_dir, agent["name"] + ".md")
    if check:
        try:
            with open(out_path, encoding="utf-8") as f:
                actual = f.read()
        except FileNotFoundError:
            actual = None
        if actual != output:
            failures.append(out_path)
        continue

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)

    print("generated " + out_path + (f" (model: {model})" if model else " (no model override)"))

if failures:
    print("sync-claude-agents: generated output is stale: " + ", ".join(failures), file=sys.stderr)
    raise SystemExit(1)
PY

# --check gates committed output. Everything below writes: symlinks into
# .claude/, then sync-mcp.sh, whose own output is gitignored.
if [[ "$check" == "true" ]]; then
  exit 0
fi

# The adapter layer itself. These four have no generator — they are hand-
# written sources that live under .agents/ so the tracked tree carries them,
# and .claude/ gets symlinks. Without this a checkout that ignores .claude/
# has no settings and no adapter, which means no hooks at all.
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mkdir -p "$repo/.claude/hooks" "$repo/.claude/skills" "$repo/.claude/rules"
link() {   # source under .agents/claude, destination under .claude
  local src="$1" dst="$2" rel="$3"
  [[ -f "$repo/$src" ]] || { echo "sync: missing source $src" >&2; return 1; }
  [[ -L "$repo/$dst" && "$(readlink "$repo/$dst")" == "$rel" ]] && return 0
  rm -f "$repo/$dst"
  ln -s "$rel" "$repo/$dst"
  echo "linked $dst"
}
link .agents/claude/settings.json .claude/settings.json    ../.agents/claude/settings.json
link .agents/claude/adapter.sh    .claude/hooks/adapter.sh ../../.agents/claude/adapter.sh
link .agents/claude/README.md     .claude/hooks/README.md  ../../.agents/claude/README.md
link .agents/claude/AGENTS.md     .claude/AGENTS.md        ../.agents/claude/AGENTS.md
ln -sfn AGENTS.md "$repo/.claude/CLAUDE.md"

# One symlink per installed skill: Claude reads .claude/skills/<name> and
# .claude/rules/<name>.md, both resolving back to the canonical copy under
# .agents/skills/, which Kimi and Codex already read natively.
for skill_dir in "$repo"/.agents/skills/*/; do
  [[ -d "$skill_dir" ]] || continue
  n="$(basename "$skill_dir")"
  ln -sfn "../../.agents/skills/$n" "$repo/.claude/skills/$n"
  ln -sfn "../../.agents/skills/$n/AGENTS.md" "$repo/.claude/rules/$n.md"
done

# Prune links whose canonical file is gone. A removed skill would otherwise
# leave a dangling link, and .agents/AGENTS.md reads a broken link as a missing
# canonical file — a real defect, not a stale mirror.
for stale in "$repo"/.claude/skills/* "$repo"/.claude/rules/*; do
  if [[ -L "$stale" && ! -e "$stale" ]]; then
    rm -f "$stale"
    echo "pruned ${stale#$repo/}"
  fi
done

# MCP + LSP connection files ride the same "edited config.json -> re-run sync"
# habit; sync-mcp.sh is a no-op-safe generator, cheap to always run.
"$(dirname "${BASH_SOURCE[0]}")/sync-mcp.sh"
